setwd("C:/Users/mauri/Desktop/Novos Testes/RRphylo")
library("U.PhyloMaker")
library("ape")
sp.list <- read.csv("plant_sample_species_list.csv")
megatree <- read.tree("plant_megatree.tre")
gen.list <- read.csv("plant_genus_list.csv")
result <- phylo.maker(sp.list, megatree, gen.list, nodes.type = 1, scenario = 3)
write.tree(result$phylo, "output_tree.tre")
write.csv(result$sp.list, "output_splist.csv")
